=== 80486858/repo-9/FixAntenna/Tester.Tests/cases.dtd
<!ELEMENT send (#PCDATA)>
<!ELEMENT cases (case)*>
<!ELEMENT case (desc | task | transport | tasksList)*>
<!ATTLIST case name CDATA #IMPLIED>
<!ATTLIST case updater CDATA #IMPLIED>
<!ATTLIST case comparator CDATA #IMPLIED>
<!ATTLIST case disableReason CDATA #IMPLIED>
<!ELEMENT desc (#PCDATA)>
<!ELEMENT param (#PCDATA)>
<!ATTLIST param name CDATA #IMPLIED>
<!ELEMENT expect (#PCDATA)>
<!ELEMENT tasksList (task)*>
<!ELEMENT task (param)*>
<!ATTLIST task className CDATA #IMPLIED>
<!ELEMENT transport (task | desc | expect | send)*>
<!ATTLIST transport className CDATA #IMPLIED>
<!ATTLIST transport host CDATA #IMPLIED>
<!ATTLIST transport port CDATA #IMPLIED>

=== 80486858/repo-9/FixAntenna/Tester.Tests/Engine/Cases.NotWork/Hang/Acceptor/ResendRequestOnLogin.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE cases SYSTEM "misc/cases.dtd" [
        <!ENTITY % content SYSTEM "misc/entity/definitions.inc">
        %content; ]>


<!--- This is scenario to check engine do logoff and reconnect if receive no answer after 2 test requests -->
<cases>
    <case name="Sequence Reset - Reset on login">
        &CLEAN_LOGS;
        &ENGINE_UP;
        <transport className="AcceptorSocketTransport" port="&PORT;">
            <!-- Ask engine to connect to FIXTester Acceptor transport -->
            &SESSION_UP;

            &RECEIVE_LOGON;
            <send>8=FIX.4.2#9=57#35=A#49=&ME;#56=&YOU;#34=2#52=20031027-14:29:11#98=0#108=5#10=126#</send>

            <!-- Send test request with msg seq num too high, expect resend request -->
            <expect>8=FIX.4.2#9=\d*#35=2#49=&YOU;#56=&ME;#34=2#52=&DATETIMEMS;#7=1#16=0#10=\d{3}#</expect>

            <!-- Send sequence reset reset with incorrect number -->
            <send>
                8=FIX.4.2#9=57#35=4#49=&ME;#56=&YOU;#34=3#52=20031027-14:29:11#122=20031027-14:29:11#43=Y#36=9#10=126#
            </send>

            <!-- Exchange with test request to ensure sequences is ok-->
            <send>8=FIX.4.2#9=57#35=1#49=&ME;#56=&YOU;#34=9#52=20031027-14:29:11#112=test01#10=126#</send>
            <expect>8=FIX\.4\.2#9=\d*#35=0#49=&YOU;#56=&ME;#34=3#112=test01#52=&DATETIMEMS;#10=\d{3}#</expect>


            <!-- logout -->
            <send>8=FIX.4.2#9=57#35=5#49=&ME;#56=&YOU;#34=10#52=20031027-14:29:11#10=126#</send>
            <expect>8=FIX\.4\.2#9=\d*#35=5#49=&YOU;#56=&ME;#34=4#52=&DATETIMEMS;#10=\d{3}#</expect>

        </transport>
        &ENGINE_DOWN;
    </case>
</cases>

=== 80486858/repo-9/FixAntenna/Tester.Tests/Engine/Cases/TestRequest/testRequestWithSeqNumGap.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cases SYSTEM "../../../cases.dtd" [
        <!ENTITY % content SYSTEM "../../../Engine/Entities/definitions.inc">
        %content; ]>
<cases>
    <case name="2 TestRequest before disconnect">
        &CLEAN_LOGS;
        <task className="FixEngine.EngineUpWithEchoApp">
            <param name="port">&ENGINE_PORT;</param>
            <param name="name">SERVER</param>
        </task>

        <transport className="InitiatorSocketTransport" host="localhost" port="&ENGINE_PORT;">
            <send>8=FIX.4.2#9=0#35=A#34=1#49=&ME;#52=&DATETIMEMS;#56=&YOU;#98=0#108=5#10=000#</send>
            <expect>8=FIX\.4\.2#9=\d{1,3}#35=A#34=1#49=&YOU;#52=&DATETIMEMS;#56=&ME;#10=\d{3}#</expect>

            <send>8=FIX.4.2#9=0#35=1#34=10#49=&ME;#52=&DATETIMEMS;#56=&YOU;#112=12345678#10=000#</send>
            <!-- TODO: RR should be sent before HBT -->
            <expect>8=FIX\.4\.2#9=\d*#35=0#34=2#49=&YOU;#56=&ME;#52=&DATETIMEMS;#112=12345678#10=\d{3}#</expect>
            <expect>8=FIX\.4\.2#9=\d*#35=2#34=3#49=&YOU;#56=&ME;#52=&DATETIMEMS;#7=2#16=0#10=\d{3}#</expect>
            <send>8=FIX.4.2#9=0#35=4#34=2#49=&ME;#52=&DATETIMEMS;#56=&YOU;#43=Y#123=Y#36=11#10=000#</send>

            <send>8=FIX.4.2#9=0#35=0#34=11#49=&ME;#52=&DATETIMEMS;#56=&YOU;#10=000#</send>
            <expect>8=FIX\.4\.2#9=\d*#35=0#34=4#49=&YOU;#56=&ME;#52=&DATETIMEMS;#10=\d{3}#</expect>

            <send>8=FIX.4.2#9=0#35=5#34=12#49=&ME;#56=&YOU;#52=&DATETIMEMS;#10=000#</send>
        </transport>
        &ENGINE_DOWN;
    </case>
</cases>

=== 80486858/repo-9/FixAntenna/Tester.Tests/Engine/Cases.NotWork/Hang/Acceptor/Two.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE cases SYSTEM "misc/cases.dtd" [
        <!ENTITY % content SYSTEM "misc/entity/definitions.inc">
        %content; ]>


<cases>
    <case name="Start session-end session, and then start again...">
        &CLEAN_LOGS;
        &ENGINE_UP;
        <transport className="AcceptorSocketTransport" port="&PORT;">
            &SESSION_UP;
            <!-- Hadnshake: Exchange with logons -->
            &RECEIVE_LOGON;
            &SEND_LOGON;
            <send>8=FIX.4.2#9=12#35=5#49=&ME;#56=&YOU;#34=2#52=20031012-12:10:22#58=123#10=123#</send>
            <expect>8=FIX\.4\.2#9=\d*#35=5#49=&YOU;#56=&ME;#34=2#52=\d{8}-\d{2}:\d{2}:\d{2}#58=[\w\s\p{P}]*#10=\d{3}#</expect>
            <expect></expect>
        </transport>
        <transport className="AcceptorSocketTransport" port="&PORT;">
            &SESSION_UP;
            <expect>8=FIX\.4\.2#9=\d*#35=A#49=&YOU;#56=&ME;#34=3#52=&DATETIMEMS;#98=0#108=5#10=\d{3}#</expect>
            <send>8=FIX.4.2#9=57#35=A#49=&ME;#56=&YOU;#34=3#52=20031027-14:29:11#98=0#108=5#10=126#</send>
            <send>8=FIX.4.2#9=12#35=5#49=&ME;#56=&YOU;#34=4#52=20031012-12:10:22#58=123#10=123#</send>
            <expect>8=FIX\.4\.2#9=\d*#35=5#49=&YOU;#56=&ME;#34=4#52=&DATETIMEMS;#58=[\w\s\p{P}]*#10=\d{3}#</expect>
        </transport>
        &ENGINE_DOWN;
    </case>
</cases>

=== 80486858/repo-9/Tests/Tester.Tests/Engine/Cases/Initiator/Fix41/14f_IncorrectDataFormat.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cases SYSTEM "../../../../cases.dtd" [
        <!ENTITY % content SYSTEM "../../../../Engine/Entities/definitions.inc">
        %content; ]>
<cases>
    <case name="14f_IncorrectDataFormat.def">
        &CLEAN_LOGS;
        &ENGINE_UP_WITH_ECHO_APP;

        <!--# @Receive message with a value in an incorrect data format (syntax) for a particular field identifier (tag number).-->
        <transport className="InitiatorSocketTransport" host="localhost" port="3000">

            <!--# logon message and response-->

            <send>8=FIX.4.1#9=123#35=A#34=1#49=TW#52=20031027-14:29:11#56=ISLD#98=0#108=2#10=000#</send>
            <expect>8=FIX\.4\.1#9=\d{1,3}#35=A#34=1#49=ISLD#52=\d{8}-\d{2}:\d{2}:\d{2}#56=TW#98=0#108=2#10=\d{3}#
            </expect>

            <!--#========================-->

            <!--# begin message exchange-->

            <!--#========================-->

            <!--#New order message with incorrect value. Qty (38) has a leading + sign-->

            <send>
                8=FIX.4.1#9=123#35=D#34=2#49=TW#52=20031027-14:29:11#56=ISLD#11=ID#21=1#40=1#54=1#38=+200.00#55=INTC#60=20031027-14:29:11#10=000#
            </send>
            <!--# expect a reject-->

            <expect>
                8=FIX\.4\.1#9=\d{1,3}#35=3#34=2#49=ISLD#52=\d{8}-\d{2}:\d{2}:\d{2}#56=TW#45=2#58=[\w\s\p{P}]*#10=\d{3}#
            </expect>

            <!--#========================-->

            <!--# end message exchange-->

            <!--#========================-->

            <!--# logout message and response-->

            <send>8=FIX.4.1#9=123#35=5#34=3#49=TW#52=20031027-14:29:11#56=ISLD#10=000#</send>
            <expect>8=FIX\.4\.1#9=\d{1,3}#35=5#34=3#49=ISLD#52=\d{8}-\d{2}:\d{2}:\d{2}#56=TW#10=\d{3}#</expect>
        </transport>
        &ENGINE_DOWN;
    </case>
</cases>

=== 80486858/repo-9/Tests/Tester.Tests/Engine/Cases/Posdup/Duplicate/duplicateRRProcessing.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cases SYSTEM "../../../../cases.dtd" [
        <!ENTITY % content SYSTEM "../../../../Engine/Entities/definitions.inc">
        %content; ]>
<cases>
    <case name="Skip duplicate RR">
        &CLEAN_LOGS;
        <task className="FixEngine.EngineUpWithEchoApp">
            <param name="port">&ENGINE_PORT;</param>
            <param name="name">SERVER</param>
            <param name="global_advancedResendRequestProcessing">true</param>
            <!--<param name="global_origSendingTimeChecking">false</param>-->
        </task>
        <!-- case POSDUPRR01 -->

        <!--Step 1. Using TCPclient send Logon with HBI=0.-->
        <!--Step 2. Using TCPclient send Heartbeat with 34=4. -->
        <!--Step 5. FIXAJ should send resend request -->
        <!--Step 6. Using TCPclient send Heartbeat with 34=5 and without 369 tag. -->
        <!--Step 7. FIXAJ should send ResendRequest without posdup -->

        <transport className="InitiatorSocketTransport" host="localhost" port="3000">

            <send>8=FIX.4.4#9=123#35=A#34=1#49=TW#52=20031027-14:29:11#56=ISLD#98=0#108=5#10=000#</send>
            <expect>
                 8=FIX\.4\.4#9=\d{1,3}#35=A#34=1#49=ISLD#52=\d{8}-\d{2}:\d{2}:\d{2}(\.\d{3})?#56=TW#10=\d{3}#
            </expect>

            <!-- send orders -->
            <send>
                8=FIX.4.4#9=0#35=D#49=TW#56=ISLD#34=2#50=1#52=00000000-00:00:00#11=cboeopt-06#1=TEST01#21=1#100=DSMD#55=MSFT#54=1#60=20100528-13:02:21#38=100#40=2#44=10#5049=ASH#5056=EHUB#5050=20100528-13:09:41.058#10=000#
            </send>
            <expect>8=FIX\.4\.4#9=\d{1,3}#35=D#34=2#10=\d{3}#</expect>

            <expect>8=FIX\.4\.4#9=\d{1,3}#35=0#34=3#10=\d{3}#</expect>

            <!--<send>-->
                <!--8=FIX.4.4#9=0#35=D#49=TW#56=ISLD#34=4#50=1#52=00000000-00:00:00#43=Y#11=cboeopt-06#1=TEST01#21=1#100=DSMD#55=MSFT#54=1#60=20100528-13:02:21#38=100#40=2#44=10#5049=ASH#5056=EHUB#5050=20100528-13:09:41.058#10=000#-->
            <!--</send>-->
            <!--<send>8=FIX.4.4#9=0#35=0#34=5#49=TW#52=20031027-14:29:11#56=ISLD#10=000#</send>-->

            <send>
                8=FIX.4.4#9=0#35=2#34=3#49=TW#52=00000000-00:00:00#56=ISLD#7=2#16=0#10=000#
            </send>
            <send>
                8=FIX.4.4#9=0#35=2#34=3#49=TW#52=00000000-00:00:00#43=Y#122=20031027-14:29:11#56=ISLD#7=2#16=0#10=000#
            </send>
            <send>8=FIX.4.4#9=0#35=0#34=4#49=TW#52=20031027-14:29:11#56=ISLD#10=000#</send>

            <expect>8=FIX\.4\.4#9=\d{1,3}#35=D#34=2#43=Y#10=\d{3}#</expect>
            <expect>8=FIX\.4\.4#9=\d{1,3}#35=4#34=3#43=Y#36=4#10=\d{3}#</expect>

            <expect>8=FIX\.4\.4#9=\d{1,3}#35=D#34=2#43=Y#10=\d{3}#</expect>
            <expect>8=FIX\.4\.4#9=\d{1,3}#35=4#34=3#43=Y#36=4#10=\d{3}#</expect>

            <expect>8=FIX\.4\.4#9=\d{1,3}#35=0#34=4#10=\d{3}#</expect>

        </transport>
        &ENGINE_DOWN;
    </case>
</cases>

=== 80486858/repo-9/FixAntenna/Tester.Tests/Engine/Cases/SeqReset/01/seq_reset_SRM04.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE cases SYSTEM "../../../../cases.dtd" [
        <!ENTITY % content SYSTEM "../../../../Engine/Entities/definitions.inc">
        %content; ]>

<cases>

    <!--case SRM04 -->
    <!--testzilla case 10b_001_SR -->
    <!--Step 1. Receive Sequence Reset (Gap Fill) message with NewSeqNo > MsgSeqNum and MsgSeqNum = to   -->
    <!--Step 2. 8=FIX.4.4 9=59 35=4 49=SNDR 56=TRGT 34=2 52=20081225-18:32:15 123=Y 36=10 10=198   	-->
    <!--Step 3. Expected SeqNum should be changed to 10 -->

    <case name="SRM04">
        &CLEAN_LOGS;
        &ENGINE_UP;
        <transport className="InitiatorSocketTransport" host="localhost" port="3000">
            <send>8=FIX.4.4#9=123#35=A#34=1#49=TW#52=20031027-14:29:11#56=ISLD#98=0#108=5#10=000#</send>
            <expect>
                 8=FIX\.4\.4#9=\d{1,3}#35=A#34=1#49=ISLD#52=\d{8}-\d{2}:\d{2}:\d{2}(\.\d{3})?#56=TW#10=\d{3}#
            </expect>

            <send>8=FIX.4.4#9=0#35=4#34=2#49=TW#52=20031027-14:29:11#56=ISLD#36=10#123=Y#10=000#</send>
            <expect>
                8=FIX\.4\.4#9=\d{1,3}#35=0#34=2#49=ISLD#52=\d{8}-\d{2}:\d{2}:\d{2}(\.\d{3})?#56=TW#10=\d{3}#
            </expect>

            <send>8=FIX.4.4#9=0#35=0#34=10#49=TW#52=20031027-14:29:11#56=ISLD#10=000#</send>            
            <expect>
                8=FIX\.4\.4#9=\d{1,3}#35=0#34=3#49=ISLD#52=\d{8}-\d{2}:\d{2}:\d{2}(\.\d{3})?#56=TW#10=\d{3}#
            </expect>
        </transport>
        &ENGINE_DOWN;
    </case>
</cases>

=== 80486858/repo-9/FixAntenna/Tester.Tests/Engine/Cases/Resend/BlockRR/maxRequestResendInBlockWithoutMultipleRRCloseWithGapFill.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cases SYSTEM "../../../../cases.dtd" [
        <!ENTITY % content SYSTEM "../../../../Engine/Entities/definitions.inc">
        %content; ]>
<cases>
    <case name="2 TestRequest before disconnect" disableReason="no next block request issued">
        &CLEAN_LOGS;
        <task className="FixEngine.EngineUpWithEchoApp">
            <param name="port">&ENGINE_PORT;</param>
            <param name="name">SERVER</param>
            <param name="global_maxRequestResendInBlock">3</param>
            <param name="global_switchOffSendingMultipleResendRequests">Yes</param>
        </task>

        <transport className="InitiatorSocketTransport" host="localhost" port="3000">
            <!-- send too high seqnum to get RR -->
            <send>8=FIX.4.4#9=0#35=A#34=8#49=&ME;#52=&DATETIMEMS;#56=&YOU;#98=0#108=1#10=000#</send>
            <expect>8=FIX\.4\.4#9=\d{1,3}#35=A#34=1#49=&YOU;#52=&DATETIMEMS;#56=&ME;#10=\d{3}#</expect>


            <expect>
                8=FIX\.4\.4#9=\d{1,3}#35=2#34=2#49=&YOU;#56=&ME;#52=&DATETIMEMS;#7=1#16=3#10=\d{3}#
            </expect>

            <!-- resend requested messages -->
            <send>
                8=FIX.4.4#9=0#35=4#34=1#49=&ME;#52=&DATETIMEMS;#56=&YOU;#43=Y#122=20031027-14:29:11#36=5#123=Y#10=000#
            </send>
            <expect>
                8=FIX\.4\.4#9=\d{1,3}#35=2#34=3#49=&YOU;#56=&ME;#52=&DATETIMEMS;#7=5#16=7#10=\d{3}#
            </expect>


            <!-- send one more too high seq num, but shouldn't be RR in answer-->
            <send>8=FIX.4.4#9=0#35=6#34=9#49=&ME;#52=&DATETIMEMS;#56=&YOU;#23=2#28=N#27=1#55=1#54=1#10=000#</send>
            <send>8=FIX.4.4#9=0#35=6#34=10#49=&ME;#52=&DATETIMEMS;#56=&YOU;#23=2#28=N#27=1#55=2#54=1#10=000#</send>
            <send>8=FIX.4.4#9=0#35=6#34=11#49=&ME;#52=&DATETIMEMS;#56=&YOU;#23=2#28=N#27=1#55=3#54=1#10=000#</send>


            <send>8=FIX.4.4#9=0#35=6#34=5#49=&ME;#52=&DATETIMEMS;#56=&YOU;#43=Y#122=20031027-14:29:11#23=2#28=N#27=1#55=4#54=1#10=000#</send>
            <expect>
                8=FIX\.4\.4#9=\d{1,3}#35=6#34=4#49=&YOU;#56=&ME;#52=&DATETIMEMS;#55=4#10=\d{3}#
            </expect>

            <send>8=FIX.4.4#9=0#35=6#34=6#49=&ME;#52=&DATETIMEMS;#56=&YOU;#43=Y#122=20031027-14:29:11#23=2#28=N#27=1#55=5#54=1#10=000#</send>
            <expect>
                8=FIX\.4\.4#9=\d{1,3}#35=6#34=5#49=&YOU;#56=&ME;#52=&DATETIMEMS;#55=5#10=\d{3}#
            </expect>
          
            <send>8=FIX.4.4#9=0#35=6#34=7#49=&ME;#52=&DATETIMEMS;#56=&YOU;#43=Y#122=20031027-14:29:11#23=2#28=N#27=1#55=6#54=1#10=000#</send>
            <expect>
                8=FIX\.4\.4#9=\d{1,3}#35=2#34=6#49=&YOU;#56=&ME;#52=&DATETIMEMS;#7=8#16=8#10=\d{3}#
            </expect>
            <expect>
                8=FIX\.4\.4#9=\d{1,3}#35=6#34=7#49=&YOU;#56=&ME;#52=&DATETIMEMS;#55=6#10=\d{3}#
            </expect>
          

            <send>8=FIX.4.4#9=0#35=6#34=7#49=&ME;#52=&DATETIMEMS;#56=&YOU;#43=Y#122=20031027-14:29:11#23=2#28=N#27=1#55=7#54=1#10=000#</send>
            <expect>
                8=FIX\.4\.4#9=\d{1,3}#35=6#34=8#49=&YOU;#56=&ME;#52=&DATETIMEMS;#55=7#10=\d{3}#
            </expect>

            <send>8=FIX.4.4#9=0#35=6#34=8#49=&ME;#52=&DATETIMEMS;#56=&YOU;#43=Y#122=20031027-14:29:11#23=2#28=N#27=1#55=8#54=1#10=000#</send>
            <expect>
                8=FIX\.4\.4#9=\d{1,3}#35=6#34=9#49=&YOU;#56=&ME;#52=&DATETIMEMS;#55=8#10=\d{3}#
            </expect>

            <!--<send>8=FIX.4.4#9=0#35=6#34=9#49=&ME;#52=&DATETIMEMS;#56=&YOU;#43=Y#122=20031027-14:29:11#23=2#28=N#27=1#55=1#54=1#10=000#</send>-->
            <expect>
                8=FIX\.4\.4#9=\d{1,3}#35=6#34=10#49=&YOU;#56=&ME;#52=&DATETIMEMS;#55=1#10=\d{3}#
            </expect>
            <expect>
                8=FIX\.4\.4#9=\d{1,3}#35=6#34=11#49=&YOU;#56=&ME;#52=&DATETIMEMS;#55=2#10=\d{3}#
            </expect>
            <expect>
                8=FIX\.4\.4#9=\d{1,3}#35=6#34=12#49=&YOU;#56=&ME;#52=&DATETIMEMS;#55=3#10=\d{3}#
            </expect>

            <send>8=FIX.4.4#9=0#35=6#34=9#49=&ME;#52=&DATETIMEMS;#56=&YOU;#23=2#28=N#27=1#55=9#54=1#10=000#</send>
            <expect>
                8=FIX\.4\.4#9=\d{1,3}#35=6#34=13#49=&YOU;#56=&ME;#52=&DATETIMEMS;#55=9#10=\d{3}#
            </expect>

        </transport>
        &ENGINE_DOWN;
    </case>
</cases>

=== 80486858/repo-9/Tests/Tester.Tests/Engine/Cases/AdvResendRequest/HighSeqAndNoProcessedFieldNotSmart.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cases SYSTEM "../../../cases.dtd" [
        <!ENTITY % content SYSTEM "../../../Engine/Entities/definitions.inc">
        %content; ]>
<cases>
    <case name="case HighSeqAndNoTag369AndNotSmart">
        &CLEAN_LOGS;
        <task className="FixEngine.EngineUpWithEchoApp">
            <param name="port">&ENGINE_PORT;</param>
            <param name="name">SERVER</param>
            <param name="global_advancedResendRequestProcessing">false</param>
        </task>
        <!-- case POSDUPRR01 -->

        <!--Step 1. Using TCPclient send Logon with HBI=0.-->
        <!--Step 2. Using TCPclient send Heartbeat with 34=4. -->
        <!--Step 5. FIXAJ should send resend request -->
        <!--Step 6. Using TCPclient send Heartbeat with 34=5 and without 369 tag. -->
        <!--Step 7. FIXAJ should send ResendRequest without posdup -->

        <transport className="InitiatorSocketTransport" host="localhost" port="3000">

            <send>8=FIX.4.4#9=123#35=A#34=1#49=TW#52=20031027-14:29:11#56=ISLD#98=0#108=5#10=000#</send>
            <expect>
                 8=FIX\.4\.4#9=\d{1,3}#35=A#34=1#49=ISLD#52=\d{8}-\d{2}:\d{2}:\d{2}(\.\d{3})?#56=TW#10=\d{3}#
            </expect>

            <send>8=FIX.4.4#9=0#35=0#34=4#49=TW#52=20031027-14:29:11#56=ISLD#10=000#</send>
            <expect>
                8=FIX\.4\.4#9=\d{1,3}#35=2#34=2#49=ISLD#52=\d{8}-\d{2}:\d{2}:\d{2}(\.\d{3})?#56=TW#7=2#16=0#10=\d{3}#
            </expect>

            <send>8=FIX.4.4#9=0#35=0#34=5#49=TW#52=20031027-14:29:11#56=ISLD#10=000#</send>
            <expect>
                8=FIX\.4\.4#9=\d{1,3}#35=2#34=3#49=ISLD#52=\d{8}-\d{2}:\d{2}:\d{2}(\.\d{3})?#56=TW#7=2#16=0#10=\d{3}#
            </expect>

        </transport>
        &ENGINE_DOWN;
    </case>
</cases>
