=== 80486858/repo-9/FixAntenna/Tester.Tests/cases.dtd
<!ELEMENT send (#PCDATA)>
<!ELEMENT cases (case)*>
<!ELEMENT case (desc | task | transport | tasksList)*>
<!ATTLIST case name CDATA #IMPLIED>
<!ATTLIST case updater CDATA #IMPLIED>
<!ATTLIST case comparator CDATA #IMPLIED>
<!ATTLIST case disableReason CDATA #IMPLIED>
<!ELEMENT desc (#PCDATA)>
<!ELEMENT param (#PCDATA)>
<!ATTLIST param name CDATA #IMPLIED>
<!ELEMENT expect (#PCDATA)>
<!ELEMENT tasksList (task)*>
<!ELEMENT task (param)*>
<!ATTLIST task className CDATA #IMPLIED>
<!ELEMENT transport (task | desc | expect | send)*>
<!ATTLIST transport className CDATA #IMPLIED>
<!ATTLIST transport host CDATA #IMPLIED>
<!ATTLIST transport port CDATA #IMPLIED>

=== 80486858/repo-9/FixAntenna/Tester.Tests/Engine/Cases/Initiator/Fix44/3b_InvalidChecksum.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cases SYSTEM "../../../../cases.dtd" [
        <!ENTITY % content SYSTEM "../../../../Engine/Entities/definitions.inc">
        %content; ]>
<cases>
    <case name="3b_InvalidChecksum.def" updater="SmartUpdater">
        &CLEAN_LOGS;
        &ENGINE_UP_WITH_ECHO_APP;

        <!--# If message has incorrect checksum, it should be ignored-->
        <transport className="InitiatorSocketTransport" host="localhost" port="3000">

            <send>8=FIX.4.4#9=0#35=A#34=1#49=TW#52=00000000-00:00:00#56=ISLD#98=0#108=5#10=000#</send>
            <expect>
                8=FIX\.4\.4#9=\d{1,3}#35=A#34=1#49=ISLD#52=\d{8}-\d{2}:\d{2}:\d{2}(\.\d{3})?#56=TW#98=0#108=5#10=\d{3}#
            </expect>

            <!--# Incorrect checksum-->
            <send>8=FIX.4.4#9=0#35=0#34=2#49=TW#52=00000000-00:00:00#56=ISLD#10=256#</send>

            <!--# Correct checksum-->
            <send>8=FIX.4.4#9=0#35=0#34=2#49=TW#52=00000000-00:00:00#56=ISLD#10=000#</send>

            <!--# Incorrect checksum-->
            <send>8=FIX.4.4#9=0#35=D#34=3#49=TW#52=00000000-00:00:00#56=ISLD#11=ID#21=3#40=1#54=1#55=INTC#38=1#10=256#</send>

            <send>8=FIX.4.4#9=0#35=0#34=4#49=TW#52=00000000-00:00:00#56=ISLD#10=000#</send>

            <!--# Resend request for missed message-->
            <expect>
                8=FIX\.4\.4#9=\d{1,3}#35=2#34=2#49=ISLD#52=\d{8}-\d{2}:\d{2}:\d{2}(\.\d{3})?#56=TW#7=3#16=0#10=\d{3}#
            </expect>

            <send>8=FIX.4.4#9=0#35=D#34=3#49=TW#52=00000000-00:00:00#43=Y#122=20031027-14:29:11#56=ISLD#11=ID#21=3#40=1#54=1#55=INTC#38=1#60=20000101-01:00:00#10=000#</send>
            
            <expect>
                8=FIX\.4\.4#9=\d{1,3}#35=D#34=3#49=ISLD#52=\d{8}-\d{2}:\d{2}:\d{2}(\.\d{3})?#56=TW#11=ID#21=3#40=1#54=1#55=INTC#38=1#60=20000101-01:00:00#
            </expect>

            <send>8=FIX.4.4#9=0#35=4#34=4#49=TW#52=00000000-00:00:00#43=Y#122=20031027-14:29:11#56=ISLD#36=5#123=Y#10=000#</send>

            <!--# logout message and response-->
            <send>8=FIX.4.4#9=0#35=5#34=5#49=TW#52=00000000-00:00:00#56=ISLD#10=000#</send>
            <expect>8=FIX\.4\.4#9=\d{1,3}#35=5#34=4#49=ISLD#52=\d{8}-\d{2}:\d{2}:\d{2}(\.\d{3})?#56=TW#10=\d{3}#
            </expect>
        </transport>
        &ENGINE_DOWN;
    </case>
</cases>

=== 80486858/repo-9/FixAntenna/Tester.Tests/Engine/Cases/Resend/AdvancedProcessing/withAdvancedRRProcessing.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cases SYSTEM "../../../../cases.dtd" [
        <!ENTITY % content SYSTEM "../../../../Engine/Entities/definitions.inc">
        %content; ]>
<cases>
    <case name="2 TestRequest before disconnect">
        &CLEAN_LOGS;
        <task className="FixEngine.EngineUpWithEchoApp">
            <param name="port">&ENGINE_PORT;</param>
            <param name="name">SERVER</param>
            <param name="global_advancedResendRequestProcessing">true</param>
        </task>

        <transport className="InitiatorSocketTransport" host="localhost" port="3000">
            <send>8=FIX.4.2#9=123#35=A#34=1#49=&ME;#52=&DATETIMEMS;#56=&YOU;#98=0#108=10#10=000#</send>
            <expect>8=FIX\.4\.2#9=\d{1,3}#35=A#34=1#49=&YOU;#52=&DATETIMEMS;#56=&ME;#10=\d{3}#</expect>


            <send>8=FIX.4.2#9=0#35=0#34=5#49=&ME;#52=&DATETIMEMS;#56=&YOU;#369=1#10=000#</send>
            <expect>8=FIX\.4\.2#9=\d{1,3}#35=2#34=2#49=&YOU;#52=&DATETIMEMS;#56=&ME;#7=2#16=0#10=\d{3}#</expect>

            <send>8=FIX.4.2#9=0#35=0#34=6#49=&ME;#52=&DATETIMEMS;#56=&YOU;#369=1#10=000#</send>
            <expect>8=FIX\.4\.2#9=\d{1,3}#35=2#34=3#49=&YOU;#52=&DATETIMEMS;#56=&ME;#43=Y#7=2#16=0#10=\d{3}#</expect>

        </transport>
        &ENGINE_DOWN;
    </case>
</cases>

=== 80486858/repo-9/Tests/Tester.Tests/Engine/Cases/SeqReset/01/seq_reset_SRM03A.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE cases SYSTEM "../../../../cases.dtd" [
        <!ENTITY % content SYSTEM "../../../../Engine/Entities/definitions.inc">
        %content; ]>

<cases>

    <!--case SRM03 A -->
    <!--testzilla case 10a_002_SR A -->
    <!--Step 1. Receive Sequence Reset (Gap Fill) message with NewSeqNo > MsgSeqNum and MsgSeqNum > than  -->
    <!--Step 2. 8=FIX.4.4 9=59 35=4 49=SNDR 56=TRGT 34=6 52=20081225-18:32:15 123=Y 36=10 10=202  	-->
    <!--Step 2. FIXAJ should send Resend Request message to Initiator with 34=2, 7=2, 16=0 -->
    <!--Step 2. 8=FIX.4.4 9=59 35=4 49=SNDR 56=TRGT 34=6 52=20081225-18:32:15 123=Y 36=10 10=202  	-->
    <!--Step 2. FIXAJ should send Log out seq to low -->

    <case name="SRM03">
        &CLEAN_LOGS;

        <task className="FixEngine.EngineUp">
            <param name="port">&ENGINE_PORT;</param>
            <param name="name">SERVER</param>
            <param name="global_resendRequestNumberOfMessagesLimit">1000</param>
            <param name="global_ignorePossDupForGapFill">false</param>
        </task>
        
        <transport className="InitiatorSocketTransport" host="localhost" port="3000">
            <send>8=FIX.4.4#9=123#35=A#34=1#49=TW#52=20031027-14:29:11#56=ISLD#98=0#108=5#10=000#</send>
            <expect>
                8=FIX\.4\.4#9=\d{1,3}#35=A#34=1#49=ISLD#52=\d{8}-\d{2}:\d{2}:\d{2}(\.\d{3})?#56=TW#10=\d{3}#
            </expect>

            <send>8=FIX.4.4#9=0#35=4#34=4#49=TW#52=20031027-14:29:11#56=ISLD#36=10#123=Y#10=000#</send>
            <expect>
                8=FIX\.4\.4#9=\d{1,3}#35=2#34=2#49=ISLD#52=\d{8}-\d{2}:\d{2}:\d{2}(\.\d{3})?#56=TW#7=2#16=0#10=\d{3}#
            </expect>

            <send>8=FIX.4.4#9=0#35=4#34=4#49=TW#52=20031027-14:29:11#56=ISLD#36=10#123=Y#10=000#</send>
            <expect>
                8=FIX\.4\.4#9=\d{1,3}#35=5#34=3#49=ISLD#52=\d{8}-\d{2}:\d{2}:\d{2}(\.\d{3})?#56=TW#10=\d{3}#
            </expect>
        </transport>
        &ENGINE_DOWN;
    </case>
</cases>

=== 80486858/repo-9/FixAntenna/Tester.Tests/Engine/Cases/Resend/EndSeqNumGreaterThanBeginSeqNum_.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cases SYSTEM "../../../cases.dtd" [
        <!ENTITY % content SYSTEM "../../../Engine/Entities/definitions.inc">
        %content; ]>
<cases>
    <case name="CASE RR">
        &CLEAN_LOGS;
        &ENGINE_UP_WITH_ECHO_APP;

        <transport className="InitiatorSocketTransport" host="localhost" port="3000">

            <send>8=FIX.4.4#9=123#35=A#34=1#49=TW#52=20031027-14:29:11#56=ISLD#98=0#108=5#10=000#</send>
            <expect>
                8=FIX\.4\.4#9=\d{1,3}#35=A#34=1#49=ISLD#52=\d{8}-\d{2}:\d{2}:\d{2}(\.\d{3})?#56=TW#10=\d{3}#
            </expect>

            <!-- send orders -->
            <send>
                8=FIX.4.4#9=0#35=D#49=TW#56=ISLD#34=2#50=1#52=00000000-00:00:00#11=cboeopt-06#1=TEST01#21=1#100=DSMD#55=MSFT#54=1#60=20100528-13:02:21#38=100#40=2#44=10#5049=ASH#5056=EHUB#5050=20100528-13:09:41.058#10=000#
            </send>
            <expect>8=FIX\.4\.4#9=\d{1,3}#35=D#10=\d{3}#</expect>
            <send>
                8=FIX.4.4#9=0#35=D#49=TW#56=ISLD#34=3#50=1#52=00000000-00:00:00#11=cboeopt-06#1=TEST01#21=1#100=DSMD#55=MSFT#54=1#60=20100528-13:02:21#38=100#40=2#44=10#5049=ASH#5056=EHUB#5050=20100528-13:09:41.058#10=000#
            </send>
            <expect>8=FIX\.4\.4#9=\d{1,3}#35=D#10=\d{3}#</expect>
            <send>
                8=FIX.4.4#9=0#35=D#49=TW#56=ISLD#34=4#50=1#52=00000000-00:00:00#11=cboeopt-06#1=TEST01#21=1#100=DSMD#55=MSFT#54=1#60=20100528-13:02:21#38=100#40=2#44=10#5049=ASH#5056=EHUB#5050=20100528-13:09:41.058#10=000#
            </send>
            <expect>8=FIX\.4\.4#9=\d{1,3}#35=D#10=\d{3}#</expect>

            <expect>8=FIX\.4\.4#9=\d{1,3}#35=0#10=\d{3}#</expect>

            <send>
                8=FIX.4.4#9=0#35=2#34=5#49=TW#52=00000000-00:00:00#43=Y#122=20031027-14:29:11#56=ISLD#7=3#16=1#10=000#
            </send>
            <expect>
                8=FIX\.4\.4#9=\d{1,3}#35=3#34=6#49=ISLD#52=\d{8}-\d{2}:\d{2}:\d{2}(\.\d{3})?#56=TW#58=[\w\s\p{P}\p{Sm}]*#10=\d{3}#
            </expect>
        </transport>
        &ENGINE_DOWN;
    </case>
</cases>

=== 80486858/repo-9/FixAntenna/Tester.Tests/Engine/Cases.NotWork/Hang/Acceptor/ReconnectCheck.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE cases SYSTEM "misc/cases.dtd" [
        <!ENTITY % content SYSTEM "misc/entity/definitions.inc">
        %content; ]>


<!--- This is scenario to check engine do logoff and reconnect if receive no answer after 2 test requests -->
<cases>
    <case name="Sequence Reset - Reset on login">
        &CLEAN_LOGS;
        &ENGINE_UP;
        <transport className="AcceptorSocketTransport" port="&PORT;">
            <!-- Ask engine to connect to FIXTester Acceptor transport -->
            &SESSION_UP;

            &RECEIVE_LOGON;
            &SEND_LOGON;
            <send>8=FIX.4.2#9=57#35=0#49=&ME;#56=&YOU;#34=2#52=20031027-14:29:11#10=126#</send>
        </transport>
        <transport className="AcceptorSocketTransport" port="&PORT;">

            <expect>8=FIX\.4\.2#9=\d*#35=A#49=&YOU;#56=&ME;#34=2#52=&DATETIMEWITHOUTMS;#98=0#108=5#10=\d{3}#</expect>

            <send>8=FIX.4.2#9=57#35=A#49=&ME;#56=&YOU;#34=3#52=20031027-14:29:11#98=0#108=5#10=126#</send>


            <!-- logout -->
            <send>8=FIX.4.2#9=57#35=5#49=&ME;#56=&YOU;#34=4#52=20031027-14:29:11#10=126#</send>
            <expect>8=FIX\.4\.2#9=\d*#35=5#49=&YOU;#56=&ME;#34=3#52=&DATETIMEMS;#10=\d{3}#</expect>

        </transport>
        &ENGINE_DOWN;
    </case>
</cases>

=== 80486858/repo-9/Tests/Tester.Tests/Engine/Cases/Initiator/Local/RespondToResendRequestWithGapFill.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE cases SYSTEM "../../../../cases.dtd" [
        <!ENTITY % content SYSTEM "../../../../Engine/Entities/definitions.inc">
        %content; ]>


<!--- This is scenario to check engine do logoff and reconnect if receive no answer after 2 test requests -->
<cases>
    <case name="Respond to Resend Request With Sequence Reset - Gap Fill">
        &CLEAN_LOGS;
        &ENGINE_UP;
        <transport className="InitiatorSocketTransport" host="localhost" port="&ENGINE_PORT;">
            &SEND_LOGON;
            &RECEIVE_LOGON;
            <!-- Exchange with test request to ensure sequences is ok-->
            <send>8=FIX.4.2#9=57#35=1#49=&ME;#56=&YOU;#34=2#52=20031027-14:29:11#112=test01#10=126#</send>
            <expect>8=FIX\.4\.2#9=\d*#35=0#49=&YOU;#56=&ME;#34=2#112=test01#52=&DATETIMEMS;#10=\d{3}#</expect>

            <!-- Send resend request (expect gap fill)-->
            <send>8=FIX.4.2#9=57#35=2#49=&ME;#56=&YOU;#34=3#52=20031027-14:29:11#7=2#16=0#10=126#</send>
            <expect>8=FIX\.4\.2#9=\d*#35=4#49=&YOU;#56=&ME;#34=2#52=&DATETIMEMS;#122=&DATETIMEMS;#43=Y#36=3#123=Y#10=\d{3}#</expect>

            <!-- Exchange with test request to ensure sequences is ok-->
            <send>8=FIX.4.2#9=57#35=1#49=&ME;#56=&YOU;#34=4#52=20031027-14:29:11#112=test01#10=126#</send>
            <expect>8=FIX\.4\.2#9=\d*#35=0#49=&YOU;#56=&ME;#34=3#112=test01#52=&DATETIMEMS;#10=\d{3}#</expect>
            <!-- logout -->
            <send>8=FIX.4.2#9=57#35=5#49=&ME;#56=&YOU;#34=5#52=20031027-14:29:11#10=126#</send>
            <expect>8=FIX\.4\.2#9=\d*#35=5#49=&YOU;#56=&ME;#34=4#52=&DATETIMEMS;#10=\d{3}#</expect>

        </transport>
        &ENGINE_DOWN;
    </case>
</cases>

=== 80486858/repo-9/Tests/Tester.Tests/Engine/Cases/Initiator/Local/SeqNumRestoreAfterTooLowSeqNum.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cases SYSTEM "../../../../cases.dtd" [
        <!ENTITY % content SYSTEM "../../../../Engine/Entities/definitions.inc">
        %content; ]>
<cases>
    <case name="Resetting sequences via Logon (if before was detected a gap/seq num too high/)">
        &CLEAN_LOGS;
        &ENGINE_UP;
        <transport className="InitiatorSocketTransport" host="localhost" port="&ENGINE_PORT;">
            <send>8=FIX.4.4#9=0#35=A#49=Tester#56=B2B#34=1#52=20031027-14:29:11#98=0#108=3#141=Y#10=126#</send>
            <expect>8=FIX\.4\.4#9=69#35=A#49=B2B#56=Tester#34=1#52=\d{8}-\d{2}:\d{2}:\d{2}(\.\d{3})?#98=0#108=3#10=\d{3}#</expect>
            <send>8=FIX.4.4#9=123#35=0#34=2#49=Tester#52=20031027-14:29:11#56=B2B#10=000#</send>
            <send>8=FIX.4.4#9=123#35=0#34=3#49=Tester#52=20031027-14:29:11#56=B2B#10=000#</send>
            <send>8=FIX.4.4#9=123#35=0#34=4#49=Tester#52=20031027-14:29:11#56=B2B#10=000#</send>
            <send>8=FIX.4.4#9=123#35=0#34=5#49=Tester#52=20031027-14:29:11#56=B2B#10=000#</send>
            <send>8=FIX.4.4#9=123#35=0#34=2#49=Tester#52=20031027-14:29:11#56=B2B#10=000#</send>
            <expect>8=FIX\.4\.4#9=\d*#35=5#49=B2B#56=Tester#34=2#52=\d{8}-\d{2}:\d{2}:\d{2}(\.\d{3})?#10=\d{3}#</expect>
        </transport>

        <task className="FixEngine.Delay">
            <param name="timeInMilis">5000</param>
        </task>
        &ENGINE_DOWN;
        &ENGINE_UP;
        <transport className="InitiatorSocketTransport" host="localhost" port="&ENGINE_PORT;">
            <send>8=FIX.4.4#9=0#35=A#49=Tester#56=B2B#34=6#52=20031027-14:29:11#98=0#108=3#10=126#</send>
            <!--<expect>8=FIX\.4\.4#9=\d*#35=A#49=B2B#56=Tester#34=1#52=\d{8}-\d{2}:\d{2}:\d{2}(\.\d{3})?#98=0#108=5#141=Y#10=\d{3}#</expect>-->
            <expect>8=FIX\.4\.4#9=\d*#35=A#49=B2B#56=Tester#34=3#52=\d{8}-\d{2}:\d{2}:\d{2}(\.\d{3})?#10=\d{3}#</expect>
            <send>8=FIX.4.4#9=0#35=0#49=Tester#56=B2B#34=7#52=20031027-14:29:11#10=126#</send>
            <expect>8=FIX\.4\.4#9=\d*#35=0#49=B2B#56=Tester#34=4#52=\d{8}-\d{2}:\d{2}:\d{2}(\.\d{3})?#10=\d{3}#</expect>
        </transport>
        &ENGINE_DOWN;
    </case>
</cases>

=== 80486858/repo-9/Tests/Tester.Tests/Engine/Cases/Resend/RRWithNextExpectedSeqNumForInitiator.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE cases SYSTEM "../../../cases.dtd" [
        <!ENTITY % content SYSTEM "../../../Engine/Entities/definitions.inc">
        %content; ]>

<cases>
    <case name="Normal.def">
        &CLEAN_LOGS;
        <task className="FixEngine.EngineUp">
            <param name="port">&ENGINE_PORT;</param>
            <param name="name">SERVER</param>
            <param name="global_handleSeqNumAtLogon">true</param>
            <param name="global_outgoingStorageIndexed">false</param>
        </task>
        <transport className="AcceptorSocketTransport" port="&PORT;">
            <task className="FixEngine.SessionUpTask">
                <param name="FixVersion">FIX.4.4</param>
                <param name="host">&HOST;</param>
                <param name="port">&PORT;</param>
                <param name="SenderCompID">Engine</param>
                <param name="TargetCompID">Tester</param>
                <param name="sessionIdName">sessionId</param>
                <param name="hbtInterval">2</param>
            </task>
            <expect>
                8=FIX\.4\.4#9=\d{1,3}#35=A#34=1#49=Engine#52=\d{8}-\d{2}:\d{2}:\d{2}\.\d{3}#56=Tester#98=0#108=2#789=1#10=\d{3}#
            </expect>
            <send>8=FIX.4.4#9=123#35=A#34=1#49=Tester#52=20031027-14:29:11#56=Engine#98=0#108=2#789=2#10=126#</send>

            <expect>8=FIX\.4\.4#9=\d{1,3}#35=0#34=2#49=Engine#56=Tester#52=\d{8}-\d{2}:\d{2}:\d{2}(\.\d{3})?#10=\d{3}#</expect>
            <!--<send>8=FIX.4.2#9=0#35=0#34=2#49=Tester#56=Engine#52=20101111-11:46:33.755#10=000#</send>-->

            <send>8=FIX.4.4#9=123#35=5#34=2#49=Tester#52=20031027-14:29:11#56=Engine#10=126#</send>

            <expect>8=FIX\.4\.4#9=\d{1,3}#35=5#34=3#49=Engine#52=\d{8}-\d{2}:\d{2}:\d{2}\.\d{3}#56=Tester#10=\d{3}#
            </expect>
            &SESSION_DOWN;
        </transport>

       <transport className="AcceptorSocketTransport" port="&PORT;">
            <task className="FixEngine.SessionUpTask">
                <param name="FixVersion">FIX.4.4</param>
                <param name="host">&HOST;</param>
                <param name="port">&PORT;</param>
                <param name="SenderCompID">Engine</param>
                <param name="TargetCompID">Tester</param>
                <param name="sessionIdName">sessionId</param>
                <param name="hbtInterval">2</param>
            </task>
            <expect>
                8=FIX\.4\.4#9=\d{1,3}#35=A#34=4#49=Engine#52=\d{8}-\d{2}:\d{2}:\d{2}\.\d{3}#56=Tester#98=0#108=2#789=3#10=\d{3}#
            </expect>
            <send>8=FIX.4.4#9=123#35=A#34=3#49=Tester#52=20031027-14:29:11#56=Engine#98=0#108=2#789=1#10=126#</send>

           <expect>
               8=FIX\.4\.4#9=\d{1,3}#35=4#34=1#49=Engine#52=\d{8}-\d{2}:\d{2}:\d{2}(\.\d{3})?#56=Tester#123=Y#36=5#10=\d{3}#
           </expect>

            <send>8=FIX.4.4#9=123#35=5#34=4#49=Tester#52=20031027-14:29:11#56=Engine#10=126#</send>

            <expect>8=FIX\.4\.4#9=\d{1,3}#35=5#34=5#49=Engine#52=\d{8}-\d{2}:\d{2}:\d{2}\.\d{3}#56=Tester#10=\d{3}#
            </expect>
            &SESSION_DOWN;
        </transport>
        &ENGINE_DOWN;

    </case>
</cases>
