=== 80486858/repo-9/FixAntenna/Tester.Tests/cases.dtd
<!ELEMENT send (#PCDATA)>
<!ELEMENT cases (case)*>
<!ELEMENT case (desc | task | transport | tasksList)*>
<!ATTLIST case name CDATA #IMPLIED>
<!ATTLIST case updater CDATA #IMPLIED>
<!ATTLIST case comparator CDATA #IMPLIED>
<!ATTLIST case disableReason CDATA #IMPLIED>
<!ELEMENT desc (#PCDATA)>
<!ELEMENT param (#PCDATA)>
<!ATTLIST param name CDATA #IMPLIED>
<!ELEMENT expect (#PCDATA)>
<!ELEMENT tasksList (task)*>
<!ELEMENT task (param)*>
<!ATTLIST task className CDATA #IMPLIED>
<!ELEMENT transport (task | desc | expect | send)*>
<!ATTLIST transport className CDATA #IMPLIED>
<!ATTLIST transport host CDATA #IMPLIED>
<!ATTLIST transport port CDATA #IMPLIED>

=== 80486858/repo-9/FixAntenna/Tester.Tests/Engine/Cases/Initiator/Fix43/2t_FirstThreeFieldsOutOfOrder.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cases SYSTEM "../../../../cases.dtd" [
        <!ENTITY % content SYSTEM "../../../../Engine/Entities/definitions.inc">
        %content; ]>
<cases>
    <case name="2t_FirstThreeFieldsOutOfOrder.def">
        &CLEAN_LOGS;
        &ENGINE_UP_WITH_ECHO_APP;

        <!--# Send messages BeginString, BodyLength and MsgType in wrong order-->
        <transport className="InitiatorSocketTransport" host="localhost" port="3000">

            <send>8=FIX.4.3#9=123#35=A#34=1#49=TW#52=20031027-14:29:11#56=ISLD#98=0#108=5#10=000#</send>
            <expect>
                8=FIX\.4\.3#9=\d{1,3}#35=A#34=1#49=ISLD#52=\d{8}-\d{2}:\d{2}:\d{2}(\.\d{3})?#56=TW#98=0#108=5#10=\d{3}#
            </expect>

            <!--# 35 is first, should be second-->

            <send>35=0#8=FI#9=123X.4.3#9=29#34=2#49=TW#52=20031027-14:29:11#56=ISLD#10=121#10=000#</send>
            <send>8=FIX.4.3#9=123#35=1#34=2#49=TW#52=20031027-14:29:11#56=ISLD#112=HELLO#10=000#</send>
            <expect>
                8=FIX\.4\.3#9=\d{1,3}#35=0#34=2#49=ISLD#52=\d{8}-\d{2}:\d{2}:\d{2}(\.\d{3})?#56=TW#112=HELLO#10=\d{3}#
            </expect>

            <!--# 34 is second, should be third-->

            <send>8=FIX.4.3#9=123#34=3#35=0#49=TW#52=20031027-14:29:11#56=ISLD#10=000#</send>
            <send>8=FIX.4.3#9=123#35=1#34=3#49=TW#52=20031027-14:29:11#56=ISLD#112=HELLO#10=000#</send>
            <expect>
                8=FIX\.4\.3#9=\d{1,3}#35=0#34=3#49=ISLD#52=\d{8}-\d{2}:\d{2}:\d{2}(\.\d{3})?#56=TW#112=HELLO#10=\d{3}#
            </expect>

            <!--# logout message and response-->

            <send>8=FIX.4.3#9=123#35=5#34=4#49=TW#52=20031027-14:29:11#56=ISLD#10=000#</send>
            <expect>8=FIX\.4\.3#9=\d{1,3}#35=5#34=4#49=ISLD#52=\d{8}-\d{2}:\d{2}:\d{2}(\.\d{3})?#56=TW#10=\d{3}#
            </expect>
        </transport>
        &ENGINE_DOWN;
    </case>
</cases>

=== 80486858/repo-9/FixAntenna/Tester.Tests/Engine/Cases/Logon/quietLogonModeDisabledTest.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE cases SYSTEM "../../../cases.dtd" [
        <!ENTITY % content SYSTEM "../../../Engine/Entities/definitions.inc">
        %content; ]>

<cases>
    <!-- this test depends on optional task, a way different for every engine -->
    <case name="test quietLogonMode option">
        &CLEAN_LOGS;
        <task className="FixEngine.EngineUp">
            <param name="port">&ENGINE_PORT;</param>
            <param name="name">SERVER</param>
            <param name="global_forceSeqNumReset">Always</param>
            <!--<param name="global_quietLogonMode">false</param>-->
        </task>
        <transport className="AcceptorSocketTransport" port="&PORT;">
            &SESSION_UP;
            <expect>8=FIX\.4\.2#9=\d*#35=A#49=Engine#56=Tester#34=1#52=&DATETIMEMS;#98=0#141=Y#108=5#10=\d{3}#</expect>
            <send>8=FIX.4.2#9=0#35=5#49=Tester#56=Engine#34=100#52=20031027-14:29:11#10=126#</send>
            <expect>8=FIX\.4\.2#9=\d*#35=2#49=Engine#56=Tester#34=2#52=&DATETIMEMS;#7=1#16=0#10=\d{3}#</expect>
            <send>8=FIX.4.2#9=0#35=4#49=Tester#56=Engine#34=1#52=20031027-14:29:11#43=Y#122=20150109-09:14:01#123=Y#36=100#10=126#</send>
            <expect>8=FIX\.4\.2#9=\d*#35=5#49=Engine#56=Tester#34=3#52=&DATETIMEMS;#58=First message is not logon#10=\d{3}#</expect>
            &SESSION_DOWN;
        </transport>
        <transport className="AcceptorSocketTransport" port="&PORT;">
            &SESSION_UP;
            <expect>8=FIX\.4\.2#9=\d*#35=A#49=Engine#56=Tester#34=1#52=&DATETIMEMS;#98=0#141=Y#108=5#10=\d{3}#</expect>
            <send>8=FIX.4.2#9=0#35=A#49=Tester#56=Engine#34=1#52=20031027-14:29:11#98=0#141=Y#108=5#10=126#</send>
            <expect>8=FIX\.4\.2#9=\d*#35=0#49=Engine#56=Tester#34=2#52=&DATETIMEMS;#10=\d{3}#</expect>
            <send>8=FIX.4.2#9=0#35=5#49=Tester#56=Engine#34=2#52=20031027-14:29:11#10=126#</send>
            <expect>8=FIX\.4\.2#9=\d*#35=5#49=Engine#56=Tester#34=3#52=&DATETIMEMS;#58=Confirming logout#10=\d{3}#</expect>
            &SESSION_DOWN;
        </transport>
        &ENGINE_DOWN;
    </case>
</cases>

=== 80486858/repo-9/FixAntenna/Tester.Tests/Engine/Cases/Resend/RRFromInitiatorAfterReconnect.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE cases SYSTEM "../../../cases.dtd" [
        <!ENTITY % content SYSTEM "../../../Engine/Entities/definitions.inc">
        <!ENTITY HBT "120">
        %content; ]>


<!--
- BBP-12204 issue -  FIXAJ: Resend request issue after initiator session reconnect
-->

<cases>
    <case name="Normal.def">
        &CLEAN_LOGS;
        <task className="FixEngine.EngineUp">
            <param name="port">&ENGINE_PORT;</param>
            <param name="name">SERVER</param>
            <param name="global_loginWaitTimeout">1000</param>
        </task>

        <transport className="AcceptorSocketTransport" port="&PORT;">
            <task className="FixEngine.SessionUpTask">
                <param name="FixVersion">FIX.4.2</param>
                <param name="host">&HOST;</param>
                <param name="port">&PORT;</param>
                <param name="SenderCompID">Engine</param>
                <param name="TargetCompID">Tester</param>
                <param name="sessionIdName">sessionId</param>
                <param name="hbtInterval">&HBT;</param>
            </task>
            <expect>
                8=FIX\.4\.2#9=\d{1,3}#35=A#34=1#49=Engine#52=\d{8}-\d{2}:\d{2}:\d{2}\.\d{3}#56=Tester#98=0#108=&HBT;#10=\d{3}#
            </expect>

            <expect>
                8=FIX\.4\.2#9=\d{1,3}#35=5#34=2#49=Engine#52=\d{8}-\d{2}:\d{2}:\d{2}\.\d{3}#56=Tester#10=\d{3}#
            </expect>

            <send>8=FIX.4.2#9=123#35=A#34=10#49=Tester#52=20031027-14:29:11#56=Engine#98=0#108=&HBT;#10=000#</send>

            <expect>
                8=FIX\.4\.2#9=\d{1,3}#35=2#34=3#49=Engine#52=\d{8}-\d{2}:\d{2}:\d{2}(\.\d{3})?#56=Tester#7=1#16=0#10=\d{3}#
            </expect>

            <send>8=FIX.4.2#9=123#35=5#34=11#49=Tester#52=20031027-14:29:11#56=Engine#10=126#</send>
             &SESSION_WAIT_DOWN;
        </transport>
        &ENGINE_DOWN;

        <transport className="AcceptorSocketTransport" port="&PORT;">
            <task className="FixEngine.SessionUpTask">
                <param name="FixVersion">FIX.4.2</param>
                <param name="host">&HOST;</param>
                <param name="port">&PORT;</param>
                <param name="SenderCompID">Engine</param>
                <param name="TargetCompID">Tester</param>
                <param name="sessionIdName">sessionId</param>
                <param name="hbtInterval">&HBT;</param>
            </task>
            <expect>
                8=FIX\.4\.2#9=\d{1,3}#35=A#34=4#49=Engine#52=\d{8}-\d{2}:\d{2}:\d{2}\.\d{3}#56=Tester#98=0#108=&HBT;#10=\d{3}#
            </expect>
            <expect>
                8=FIX\.4\.2#9=\d{1,3}#35=5#34=5#49=Engine#52=\d{8}-\d{2}:\d{2}:\d{2}\.\d{3}#56=Tester#10=\d{3}#
            </expect>

            <send>8=FIX.4.2#9=123#35=A#34=20#49=Tester#52=20031027-14:29:11#56=Engine#98=0#108=&HBT;#10=000#</send>
            <!--
                FIXAJ still have to request messages started from 34=3 (7=3) bat due to bug BBP-12204 it requested 7=4
             -->
            <expect>
                8=FIX\.4\.2#9=\d{1,3}#35=2#34=6#49=Engine#52=\d{8}-\d{2}:\d{2}:\d{2}(\.\d{3})?#56=Tester#7=1#16=0#10=\d{3}#
            </expect>

            <send>
                8=FIX.4.2#9=0#35=4#34=3#49=Tester#52=20031027-14:29:11#56=Engine#43=Y#122=20031027-14:29:11#123=Y#36=21#10=000#
            </send>

            <send>8=FIX.4.2#9=123#35=5#34=21#49=Tester#52=20031027-14:29:11#56=Engine#10=126#</send>
            &SESSION_DOWN;
        </transport>
        &ENGINE_DOWN;
    </case>
</cases>

=== 80486858/repo-9/FixAntenna/Tester.Tests/Engine/Cases.NotWork/Hang/Acceptor/RespondToResendRequestsWhileLoggingOut.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE cases SYSTEM "misc/cases.dtd" [
        <!ENTITY % content SYSTEM "misc/entity/definitions.inc">
        %content; ]>


<!--- This is scenario to check engine properly handle resend requests while logging out -->
<!--
Expected flow:
engine sends logout, but instead of logout receives resend request.
Engine should not logout until receives logout answer from counterparty!!!
It should propertly handle this situation and resend all requested messages.
 -->
<cases>
    <case name="Respond properly to resend request on logout">

        &CLEAN_LOGS;

        &ENGINE_UP;
        <transport className="AcceptorSocketTransport" port="&PORT;">
            <!-- Ask engine to connect to FIXTester Acceptor transport -->
            &SESSION_UP;

            <!-- Hadnshake: Exchange with logons -->
            &RECEIVE_LOGON;
            &SEND_LOGON;

            <!-- Exchange with test request to ensure sequences is ok-->
            <send>8=FIX.4.2#9=57#35=1#49=&ME;#56=&YOU;#34=2#52=20031027-14:29:11#112=test01#10=126#</send>
            <expect>8=FIX\.4\.2#9=\d*#35=0#49=&YOU;#56=&ME;#34=2#112=test01#52=&DATETIMEMS;#10=\d{3}#</expect>

            <!-- Ask engine to send 1 dummy order message to FIXTester Acceptor transport -->
            &SEND_MESSAGE;
            <expect>8=FIX\.4\.2#9=\d*#35=D#49=&YOU;#56=&ME;#11=ORD:1019746829718#34=3#52=&DATETIMEMS;#10=\d{3}#</expect>
            <!-- And shutdown session. This means engine should send us logout and wait for our reponse -->
            &SESSION_DOWN;
            <expect>8=FIX\.4\.2#9=\d*#35=5#49=&YOU;#56=&ME;#34=4#52=&DATETIMEMS;#10=\d{3}#</expect>

            <!-- But we weirdly pretend we don't receive any previous message. And send resend request instead of logout -->
            <send>8=FIX.4.2#9=57#35=2#49=&ME;#56=&YOU;#34=3#52=20031027-14:29:11#7=2#16=0#10=126#</send>

            <!-- Engine should send us gap fill for hearbeat and resend order with possDup=Y and OrigSendingTime!!!-->
            <expect>8=FIX\.4\.2#9=\d*#35=4#49=&YOU;#56=&ME;#34=2#52=&DATETIMEMS;#122=&DATETIMEMS;#43=Y#36=3#123=Y#10=\d{3}#</expect>
            <expect>8=FIX\.4\.2#9=\d*#35=D#49=&YOU;#56=&ME;#34=3#52=&DATETIMEMS;#43=Y#122=&DATETIMEMS;#43=Y#10=\d{3}#
            </expect>
            <expect>8=FIX\.4\.2#9=\d*#35=4#49=&YOU;#56=&ME;#34=4#52=&DATETIMEMS;#122=&DATETIMEMS;#43=Y#36=5#123=Y#10=\d{3}#</expect>


            <send>8=FIX.4.2#9=123#35=5#49=&ME;#56=&YOU;#34=4#52=20031027-14:29:11#10=123#</send>
            <!-- should disconnet -->
            <expect></expect>

        </transport>
        <transport className="AcceptorSocketTransport" port="&PORT;">
            <!-- Ask engine to connect to FIXTester Acceptor transport -->
            &SESSION_UP;
            <!-- Hadnshake: Exchange with logons -->
            <expect>8=FIX\.4\.2#9=\d*#35=A#49=&YOU;#56=&ME;#34=5#52=&DATETIMEMS;#98=0#108=5#10=\d{3}#
            </expect>
            <send>8=FIX.4.2#9=57#35=A#49=&ME;#56=&YOU;#34=5#52=20031027-14:29:11#98=0#108=5#10=126#</send>
            <!-- Exchange with test request to ensure sequences is ok-->
            <send>8=FIX.4.2#9=57#35=1#49=&ME;#56=&YOU;#34=6#52=20031027-14:29:11#112=test01#10=126#</send>
            <expect>8=FIX\.4\.2#9=\d*#35=0#49=&YOU;#56=&ME;#34=6#112=test01#52=&DATETIMEMS;#10=\d{3}#</expect>

            <!-- logoff to speed up engine shutdown time-->
            <send>8=FIX.4.2#9=123#35=5#49=&ME;#56=&YOU;#34=7#52=20031027-14:29:11#10=123#</send>
        </transport>
        &ENGINE_DOWN;
    </case>
</cases>

=== 80486858/repo-9/Tests/Tester.Tests/Engine/Cases/Acceptor/GarbledCheck.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE cases SYSTEM "../../../cases.dtd" [
        <!ENTITY % content SYSTEM "../../../Engine/Entities/definitions.inc">
        %content; ]>


<!--- This is scenario to check engine do logoff and reconnect if receive no answer after 2 test requests -->
<cases>
    <case name="Garbled">
        &CLEAN_LOGS;
        &ENGINE_UP;
        <transport className="AcceptorSocketTransport" port="&PORT;">
            <!-- Ask engine to connect to FIXTester Acceptor transport -->
            &SESSION_UP;

            &RECEIVE_LOGON;
            &SEND_LOGON;
            <send>11111111111111111111111111111111111111111111111111111#10=122#</send>
            <send>8=FIX.4.2#9=57#35=0#49=&ME;#56=&YOU;#34=2#52=20031027-14:29:11#10=126#</send>
            <expect>8=FIX\.4\.2#9=\d*#35=0#49=&YOU;#56=&ME;#34=2#52=&DATETIMEMS;#10=\d{3}#</expect>
            <!-- logout -->
            <send>8=FIX.4.2#9=57#35=5#49=&ME;#56=&YOU;#34=3#52=20031027-14:29:11#10=126#</send>
            <expect>8=FIX\.4\.2#9=\d*#35=5#49=&YOU;#56=&ME;#34=3#52=&DATETIMEMS;#10=\d{3}#</expect>

        </transport>
        <!--transport className="AcceptorSocketTransport" port="&PORT;">

            <expect>8=FIX\.4\.2#9=\d*#35=A#49=&YOU;#56=&ME;#34=2#52=&DATETIMEWITHOUTMS;#98=0#108=5#10=\d{3}#</expect>

            <send>8=FIX.4.2#9=57#35=A#49=&ME;#56=&YOU;#34=3#52=20031027-14:29:11#98=0#108=5#10=126#</send-->


        <!-- logout -->
        <!--send>8=FIX.4.2#9=57#35=5#49=&ME;#56=&YOU;#34=4#52=20031027-14:29:11#10=126#</send>
            <expect>8=FIX\.4\.2#9=\d*#35=5#49=&YOU;#56=&ME;#34=3#52=&DATETIMEMS;#10=\d{3}#</expect>

        </transport-->
        &ENGINE_DOWN;
    </case>
</cases>

=== 80486858/repo-9/FixAntenna/Tester.Tests/Engine/Cases/Cme/CmeProcessExpiredMessagesFromQueue.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE cases SYSTEM "../../../cases.dtd" [
        <!ENTITY % content SYSTEM "../../../Engine/Entities/definitions.inc">
        %content; ]>

<cases>
  <case name="CME specification test Process expired messages from queue">
    &CLEAN_LOGS;

    <task className="FixEngine.SetGlobalConfig">
      <param name="sourceFile">./Engine/Cases/Cme/cme_config.properties</param>
    </task>

    <task className="FixEngine.EngineUpWithEchoApp">
      <param name="port">&ENGINE_PORT;</param>
      <param name="name">SERVER</param>
    </task>


    <transport className="InitiatorSocketTransport" host="localhost" port="&ENGINE_PORT;">

        <send>    8=FIX.4.2#9=123#35=A#34=1#49=CME#52=20031027-14:29:11.123#56=B08004N#98=0#108=5#10=000#</send>
        <expect>  8=FIX\.4\.2#9=\d{1,3}#35=A#34=1#49=B08004N#52=\d{8}-\d{2}:\d{2}:\d{2}(\.\d{3})?#56=CME#10=\d{3}#</expect>


        <send>    8=FIX.4.2#9=307#35=8#34=5#369=1#52=20031027-14:29:11.123#49=CME#50=99#56=B08004N#57=0J4L#143=US#17=0005A#10=000#</send>
        <expect>  8=FIX\.4\.2#9=\d{1,3}#35=2#34=2#49=B08004N#52=\d{8}-\d{2}:\d{2}:\d{2}(\.\d{3})?#56=CME#7=2#16=0#10=\d{3}#</expect>


        <send>    8=FIX.4.2#9=307#35=8#34=6#369=1#52=20031027-14:29:11.123#49=CME#50=99#56=B08004N#57=0J4L#143=US#17=0006A#10=000#</send>
        <send>    8=FIX.4.2#9=307#35=8#34=7#369=1#52=20031027-14:29:11.123#49=CME#50=99#56=B08004N#57=0J4L#143=US#17=0007A#10=000#</send>


        <send>    8=FIX.4.2#9=307#35=4#34=2#369=2#52=20031027-14:29:11.123#43=Y#49=CME#50=99#56=B08004N#57=0J4L#143=US#36=1000#123=Y#10=000#</send>


        <send>    8=FIX.4.2#9=307#35=8#34=1000#369=2#52=20031027-14:29:11.123#49=CME#50=99#56=B08004N#57=0J4L#143=US#17=1000A#10=000#</send>
        <expect>  8=FIX\.4\.2#9=\d{1,3}#35=8#34=3#49=B08004N#52=\d{8}-\d{2}:\d{2}:\d{2}(\.\d{3})?#56=CME#17=1000A#10=\d{3}#</expect>


        <send>    8=FIX.4.2#9=123#35=5#34=1001#49=CME#52=20031027-14:29:11#56=B08004N#10=000#    </send>
        <expect>  8=FIX\.4\.2#9=\d{1,3}#35=5#34=4#49=B08004N#52=\d{8}-\d{2}:\d{2}:\d{2}(\.\d{3})?#56=CME#10=\d{3}#</expect>

    </transport>

    &ENGINE_DOWN;
  </case>
</cases>

=== 80486858/repo-9/FixAntenna/Tester.Tests/Engine/Cases/Resend/BBP19449_RRAfterReconnect.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cases SYSTEM "../../../cases.dtd" [
        <!ENTITY % content SYSTEM "../../../Engine/Entities/definitions.inc">
        %content; ]>
<cases>
    <case name="BBP-19499: Engine goes to infinite loop during session connect and sequences reset">
        &CLEAN_LOGS;
        <task className="FixEngine.EngineUpWithEchoApp">
            <param name="port">&ENGINE_PORT;</param>
            <param name="name">SERVER</param>
            <param name="reset">true</param>
            <param name="global_ignoreResetSeqNumFlagOnReset">true</param>
            <param name="global_switchOffSendingMultipleResendRequests">true</param>
        </task>

        <transport className="InitiatorSocketTransport" host="localhost" port="&ENGINE_PORT;">
            <send>8=FIX.4.4#9=123#35=A#34=1#49=TW#52=20031027-14:29:11#56=ISLD#98=0#108=5#10=000#</send>
            <expect>
                8=FIX\.4\.4#9=\d{1,3}#35=A#34=1#49=ISLD#52=\d{8}-\d{2}:\d{2}:\d{2}(\.\d{3})?#56=TW#10=\d{3}#
            </expect>

            <send>
                8=FIX.4.4#9=123#35=D#34=2#49=TW#52=20031027-14:29:11#43=Y#122=20031027-14:29:11#56=ISLD#11=ID#21=1#40=1#54=1#38=200#55=INTC#60=20031027-14:29:11#10=000#
            </send>
            <expect>
                8=FIX\.4\.4#9=\d{1,3}#35=D#34=2#49=ISLD#52=\d{8}-\d{2}:\d{2}:\d{2}(\.\d{3})?#56=TW#10=\d{3}#
            </expect>

            <send>8=FIX.4.4#9=123#35=5#34=3#49=TW#52=20031027-14:29:11#56=ISLD#10=000#</send>
            <expect>8=FIX\.4\.4#9=\d{1,3}#49=ISLD#52=\d{8}-\d{2}:\d{2}:\d{2}(\.\d{3})?#56=TW#10=\d{3}#</expect>
        </transport>

        <task className="FixEngine.SessionAwaitDisconnectTask">
          <param name="sessionIdName">ISLD-TW</param>
        </task>

        <transport className="InitiatorSocketTransport" host="localhost" port="&ENGINE_PORT;">
            <send>8=FIX.4.4#9=123#35=A#34=4#49=TW#52=20031027-14:29:11#56=ISLD#98=0#108=5#10=000#</send>
            <expect>
                8=FIX\.4\.4#9=\d{1,3}#35=A#34=1#49=ISLD#52=\d{8}-\d{2}:\d{2}:\d{2}(\.\d{3})?#56=TW#10=\d{3}#
            </expect>
            <expect>
                8=FIX\.4\.4#9=\d{1,3}#35=2#34=2#49=ISLD#52=\d{8}-\d{2}:\d{2}:\d{2}(\.\d{3})?#56=TW#7=1#16=0#10=\d{3}#
            </expect>

            <send>8=FIX.4.4#9=123#35=5#34=5#49=TW#52=20031027-14:29:11#56=ISLD#10=000#</send>
            <expect>8=FIX\.4\.4#9=\d{1,3}#49=ISLD#52=\d{8}-\d{2}:\d{2}:\d{2}(\.\d{3})?#56=TW#10=\d{3}#</expect>
        </transport>

      <task className="FixEngine.SessionAwaitDisconnectTask">
        <param name="sessionIdName">ISLD-TW</param>
      </task>

      <transport className="InitiatorSocketTransport" host="localhost" port="&ENGINE_PORT;">
            <send>8=FIX.4.4#9=123#35=A#34=6#49=TW#52=20031027-14:29:11#56=ISLD#98=0#108=5#10=000#</send>
            <expect>
                8=FIX\.4\.4#9=\d{1,3}#35=A#34=1#49=ISLD#52=\d{8}-\d{2}:\d{2}:\d{2}(\.\d{3})?#56=TW#10=\d{3}#
            </expect>
            <expect>
                8=FIX\.4\.4#9=\d{1,3}#35=2#34=2#49=ISLD#52=\d{8}-\d{2}:\d{2}:\d{2}(\.\d{3})?#56=TW#7=1#16=0#10=\d{3}#
            </expect>

            <send>8=FIX.4.4#9=123#35=5#34=7#49=TW#52=20031027-14:29:11#56=ISLD#10=000#</send>
            <expect>8=FIX\.4\.4#9=\d{1,3}#49=ISLD#52=\d{8}-\d{2}:\d{2}:\d{2}(\.\d{3})?#56=TW#10=\d{3}#</expect>
        </transport>
        &ENGINE_DOWN;
    </case>
</cases>

=== 80486858/repo-9/Tests/Tester.Tests/Engine/Cases/Initiator/Fix40/1a_ValidLogonMsgSeqNumTooHigh.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cases SYSTEM "../../../../cases.dtd" [
        <!ENTITY % content SYSTEM "../../../../Engine/Entities/definitions.inc">
        %content; ]>
<cases>
    <case name="1a_ValidLogonMsgSeqNumTooHigh.def">
        &CLEAN_LOGS;
        &ENGINE_UP_WITH_ECHO_APP;

        <!--# resend request-->
        <transport className="InitiatorSocketTransport" host="localhost" port="3000">

            <send>8=FIX.4.0#9=123#35=A#34=5#49=TW#52=20031027-14:29:11#56=ISLD#98=0#108=5#10=000#</send>
            <expect>8=FIX\.4\.0#9=\d{1,3}#35=A#34=1#49=ISLD#52=\d{8}-\d{2}:\d{2}:\d{2}#56=TW#98=0#108=5#10=\d{3}#
            </expect>

            <expect>8=FIX\.4\.0#9=\d{1,3}#35=2#34=2#49=ISLD#52=\d{8}-\d{2}:\d{2}:\d{2}#56=TW#7=1#16=999999#10=\d{3}#
            </expect>

            <!--# logout message and response-->
            <send>8=FIX.4.0#9=123#35=4#34=6#49=TW#52=20031027-14:29:11#56=ISLD#123=N#36=7#10=000#</send>
            <send>8=FIX.4.0#9=123#35=5#34=7#49=TW#52=20031027-14:29:11#56=ISLD#10=000#</send>
            <expect>8=FIX\.4\.0#9=\d{1,3}#35=5#34=3#49=ISLD#52=\d{8}-\d{2}:\d{2}:\d{2}#56=TW#10=\d{3}#</expect>
        </transport>
        &ENGINE_DOWN;
    </case>
</cases>
